src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Service\UploaderHelper;
use App\Service\UploadHelper;

#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 128)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $body = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $fileName = null;

    #[ORM\OneToMany(mappedBy: 'article', targetEntity: ArticleReference::class)]
    #[ORM\OrderBy(['position'=>'ASC'])]
    private Collection $reference;

    public function __construct()
    {
        $this->reference = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): static
    {
        $this->body = $body;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(?string $fileName): static
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getImagePath()
    {
        return  UploadHelper::ARTICLE_IMAGE . '/'.$this->getFileName();
    }

    /**
     * @return Collection<int, ArticleReference>
     */
    public function getReference(): Collection
    {
        return $this->reference;
    }

    
}

src/Form/ArticleFormType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;

class ArticleFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('body');

        $imageConstraints = [
            new Image([
                'maxSize' => '5M'
            ])
         ];

         $builder
            ->add('fileNameImage', FileType::class,
                ['mapped' => false,
                'required' => false,
                'constraints' => $imageConstraints, 
                              ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('body')
            ->add('fileName')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

templates/form/_form_article.html.twig
{{ form_start(articleForm) }}
    {{ form_row(articleForm.title, {
        label: 'Article title'
    }) }}
     <div class="row">
        <div class="col-sm-9">
            {{ form_row(articleForm.fileNameImage, {
                attr: {
                    'placeholder': 'Preselected image'
                }
            }) }}
        </div>
        <div class="col-sm-3">
            {% if articleForm.vars.data.fileName %}
                <a href="{{ uploaded_asset(articleForm.vars.data.imagePath) }}" target="_blank">
                <img src="{{ articleForm.vars.data.imagePath|imagine_filter('squared_thumbnail_small') }}" height="100">
                </a>
            {% endif %}
        </div>
    </div>
     {{ form_row(articleForm.body, {
        label: 'Article body'
     }) }}
   
    <button type="submit" class="btn btn-primary" value="Send">Publish</button>
    {{ form_end(articleForm) }}  

templates/form/edit_form.html.twig
{% extends 'base.html.twig' %}
{% block title %}Form for Edit{% endblock %}
{% block body %}
    <h1>Form for fake upload</h1>
     <div class="row">
        <div class="col-sm-8">
            <h3>Details</h3>
                {{ include('/form/_form_article.html.twig',  {
                    button_text: 'Update!'
            }) }}
        </div>

        <div class="col-sm-4">
            <h3>References</h3>
                 <ul class="list-group small js-reference-list" data-url="{{ path('app_article_list_references', {id: article.id}) }}">
                 </ul>
                
                <hr>
              <form action="{{ path('app_article_reference_add', {id:article.id}) }}" method="POST" enctype="multipart/form-data" class="dropzone js-reference-dropzone">
               
            </form>
        </div>
    </div>
    <hr>
{% endblock %}
{% block javascript %}
     <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.js" integrity="sha256-cs4thShDfjkqFGk5s2Lxj35sgSRr4MRcyccmi0WKqCM=" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.8.3/Sortable.min.js" integrity="sha256-uNITVqEk9HNQeW6mAAm2PJwFX2gN45l8a4yocqsFI6I=" crossorigin="anonymous"></script>
{% endblock %}
{% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.1/min/dropzone.min.css" integrity="sha256-e47xOkXs1JXFbjjpoRr1/LhVcqSzRmGmPqsrUQeVs+g=" crossorigin="anonymous" />

{% endblock %}
{% endblock %}

templates/form/test_form.html.twig
{% extends 'base.html.twig' %}
{% block title %}Form{% endblock %}
{% block body %}
    <h1>Form for fake upload</h1>
    {{ include('/form/_form_article.html.twig') }}
    <hr>
{% endblock %}